title: "Bilal Olakunle Kareem - DevSecOps Professional"
email: contactbilal05@gmail.com
description: >-
  Bilal Olakunle Kareem is a Cyber Security Analyst dedicated to leveraging expertise in security solutions to drive efficiency and innovation in technology environments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://crescenttech29.github.io/technix.io" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5

# Social Links
github_username: contactbilal05
linkedin_username: bilaldevsec


